export const COURSES = [
    {
        id: 1,
        title: "Complete Web Development Bootcamp 2026",
        instructor: "Dr. Angela Yu",
        category: "Development",
        rating: 4.8,
        reviews: "12,450",
        duration: "65 Total Hours",
        price: 151984,
        isFree: false,
        level: "Beginner",
        description: "Master web development from scratch with HTML, CSS, JavaScript, React, Node.js, and more. Build real-world projects.",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 2,
        title: "Deep Learning Specialization",
        instructor: "Andrew Ng",
        category: "Data Science",
        rating: 4.9,
        reviews: "45,210",
        duration: "120 Total Hours",
        price: 0,
        isFree: true,
        level: "Intermediate",
        description: "Learn neural networks, deep learning, and AI. Build career-defining projects with TensorFlow and Python.",
        image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 3,
        title: "UI/UX Design Masterclass: Strategy and Tools",
        instructor: "Gary Simon",
        category: "Design",
        rating: 4.7,
        reviews: "8,900",
        duration: "25 Total Hours",
        price: 79984,
        isFree: false,
        level: "Intermediate",
        description: "Master user interface and experience design with Figma, Adobe XD, and industry-standard design principles.",
        image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 4,
        title: "Financial Markets & Investment Strategy",
        instructor: "Robert Shiller",
        category: "Business",
        rating: 4.6,
        reviews: "15,600",
        duration: "40 Total Hours",
        price: 127984,
        isFree: false,
        level: "Beginner",
        description: "Understand stocks, bonds, derivatives, and portfolio management. Learn investment strategies from a Nobel laureate.",
        image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 5,
        title: "The Art of Negotiation",
        instructor: "Chris Voss",
        category: "Marketing",
        rating: 4.9,
        reviews: "22,100",
        duration: "15 Total Hours",
        price: 143984,
        isFree: false,
        level: "Advanced",
        description: "Learn FBI-tested negotiation tactics to get better deals in business and life. Master persuasion techniques.",
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 6,
        title: "Python for Data Science and Machine Learning",
        instructor: "Jose Portilla",
        category: "Development",
        rating: 4.8,
        reviews: "85,400",
        duration: "25 Total Hours",
        price: 0,
        isFree: true,
        level: "Intermediate",
        description: "Use Python for data analysis, visualization, and machine learning with NumPy, Pandas, Matplotlib, and Scikit-Learn.",
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 7,
        title: "Modern React with Redux",
        instructor: "Stephen Grider",
        category: "Development",
        rating: 4.7,
        reviews: "10,200",
        duration: "40 Total Hours",
        price: 87984,
        isFree: false,
        level: "Intermediate",
        description: "Build dynamic web apps with React and Redux. Master hooks, context, and state management for modern applications.",
        image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 8,
        title: "Machine Learning A-Z™: AI, Python & R",
        instructor: "Kirill Eremenko",
        category: "Data Science",
        rating: 4.6,
        reviews: "30,500",
        duration: "45 Total Hours",
        price: 111984,
        isFree: false,
        level: "Intermediate",
        description: "Create machine learning algorithms in Python and R. Learn regression, classification, clustering, and deep learning.",
        image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 9,
        title: "Graphic Design Masterclass",
        instructor: "Lindsay Marsh",
        category: "Design",
        rating: 4.8,
        reviews: "12,100",
        duration: "30 Total Hours",
        price: 63984,
        isFree: false,
        level: "Beginner",
        description: "Learn Photoshop, Illustrator, and InDesign. Create logos, branding, and professional designs from scratch.",
        image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 10,
        title: "Business Strategy from Top 1% of Consultants",
        instructor: "Davis Nguyen",
        category: "Business",
        rating: 4.9,
        reviews: "5,400",
        duration: "10 Total Hours",
        price: 207984,
        isFree: false,
        level: "Advanced",
        description: "Learn consulting frameworks, problem-solving techniques, and strategic thinking from McKinsey and BCG veterans.",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 11,
        title: "Digital Marketing Masterclass",
        instructor: "Phil Ebiner",
        category: "Marketing",
        rating: 4.5,
        reviews: "18,200",
        duration: "35 Total Hours",
        price: 31984,
        isFree: false,
        level: "Beginner",
        description: "Master SEO, social media marketing, email campaigns, and Google Ads. Build a complete digital marketing strategy.",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800"
    },
    {
        id: 12,
        title: "Music Theory Comprehensive",
        instructor: "Jason Allen",
        category: "Music",
        rating: 4.8,
        reviews: "7,800",
        duration: "12 Total Hours",
        price: 47984,
        isFree: false,
        level: "Beginner",
        description: "Understand scales, chords, harmony, and composition. Perfect for musicians, producers, and songwriters.",
        image: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&q=80&w=800"
    }
];

export const CATEGORIES = [
    "All", "Development", "Data Science", "Design", "Business", "Marketing", "Music"
];
